---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: syncer
  namespace: lmxia
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebindingadmin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: syncer
    namespace: lmxia
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus
  namespace: lmxia
  labels:
    app: octopus
spec:
  selector:
    matchLabels:
      app: octopus
  template:
    metadata:
      labels:
        app: octopus
    spec:
      containers:
        - name: octopus
          image: lmxia/octopus:v12
          securityContext:
            privileged: true
          env:
            - name: OCTOPUS_CLUSTERID
              value: hub
            - name: OCTOPUS_HUBURL
              value: https://121.41.31.123:6443
            - name: OCTOPUS_LOCALNAMESPACE
              value: syncer-operator
            - name: OCTOPUS_SHARENAMESPACE
              value: syncer-operator
            - name: OCTOPUS_CIDR
              value: 10.112.0.0/12
            - name: OCTOPUS_ISHUB
              value: "True"
            - name: OCTOPUS_ENDPOINT
              value: 121.41.31.123
      serviceAccountName: syncer

---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: octopus
  name: wireguard-service
  namespace: lmxia
spec:
  type: NodePort
  ports:
    - port: 31820
      nodePort: 31820
      protocol: UDP
      targetPort: 31820
  selector:
    app: octopus